name: 'test_proj'
version: '1.0.0'
config-version: 2

profile: 'test_proj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Enterprise-grade model configurations
models:
  test_proj:

    # Staging layer: Lightweight views, organized by source system
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: "#8BC34A"  # Green in dbt docs

      # Source-specific configs
      jaffle_shop:
        +tags: ["jaffle_shop", "daily", "staging"]
        +meta:
          owner: "data-engineering@company.com"
          layer: "staging"

    # Intermediate layer: Ephemeral by default (not materialized)
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +docs:
        node_color: "#FFC107"  # Yellow in dbt docs

      # Domain-specific configs
      finance:
        +tags: ["finance", "intermediate"]
        +meta:
          owner: "finance-analytics@company.com"
          layer: "intermediate"

    # Marts layer: Tables for production use
    marts:
      +materialized: table
      +schema: marts
      +docs:
        node_color: "#2196F3"  # Blue in dbt docs

      # Core domain (cross-functional entities)
      core:
        +tags: ["core", "critical", "marts"]
        +meta:
          owner: "data-engineering@company.com"
          layer: "marts"
          criticality: "high"

        # Dimension tables
        +dim_*:
          +tags: ["dimension"]
          +meta:
            model_type: "dimension"

        # Fact tables (could be incremental at scale)
        +fct_*:
          +materialized: table  # Change to incremental for large datasets
          +tags: ["fact"]
          +meta:
            model_type: "fact"

# Seeds configuration
seeds:
  test_proj:
    +schema: seeds
    +quote_columns: false

# Snapshots configuration (for SCD Type 2)
snapshots:
  test_proj:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Tests configuration
tests:
  test_proj:
    +severity: warn  # Don't fail builds on test failures by default

    marts:
      +severity: error  # But fail on critical mart tests

# Global variables (can be overridden in profiles.yml)
vars:
  # Date range for date dimension
  date_dimension_start: '2018-01-01'
  date_dimension_end: '2030-12-31'

  # Fiscal year settings
  fiscal_year_start_month: 4  # April
